// #region USUARIOS

### 
GET http://localhost:3000/api/usuario

###
GET http://localhost:3000/api/usuario/5

### POST
POST http://localhost:3000/api/usuario
Content-Type: application/json

{
  "img_url": "imagen.jpg",
  "nombre": "Federico",
  "apellido": "Cordova",
  "documento": "79456989",
  "puntos": 50,
  "tipo_doc": "DNI",
  "telefono": "99999998",
  "validacion": false
}

### PUT
PUT http://localhost:3000/api/usuario/5
Content-Type: application/json

{
  "img_url": "usuario5.jpg",
  "nombre": "Luna",
  "apellido": "Sánchez",
  "documento": "34567891",
  "puntos": 180,
  "tipo_doc": "DNI",
  "telefono": "946538522"
}

### PATCH
PATCH http://localhost:3000/api/usuario/22
Content-Type: application/json

{
  "telefono": "00000002"
}

### DELETE
DELETE http://localhost:3000/api/usuario/22



/////// #region PERSONAL /////// 



### Obtener todo el personal
GET http://localhost:3000/api/personal

### Obtener todo el personal por ID
GET http://localhost:3000/api/personal/7


### POST
POST http://localhost:3000/api/personal
Content-Type: application/json

{
  "nombre": "Fausto",
  "apellido": "Cordova",
  "contrasena": "123456",
  "documento": "85652145",
  "telefono": "99899988",
  "tipo_doc": "DNI",
  "rol": "vendedor"
}

### PUT
PUT http://localhost:3000/api/personal/8
Content-Type: application/json

{
  "nombre": "Fausto",
  "apellido": "Cordova",
  "contrasena": "87654321*",
  "documento": "85652145",
  "telefono": "99899988",
  "tipo_doc": "DNI",
  "rol": "vendedor"
}

### PATCH
PATCH http://localhost:3000/api/personal/8
Content-Type: application/json

{
  "contrasena": "qwerty12345"
}

### DELETE
DELETE http://localhost:3000/api/personal/8

###
GET http://localhost:3000/api/personal




























### Mostrar todas las peliculas
GET http://localhost:1234/movies

### Mostrar la pelicula por su ID
GET http://localhost:1234/movies/06d537cd-f872-11ee-a6cb-0a0027000009

### MOstrar las peliculas por su anio
GET http://localhost:1234/movies/year/1994

### Mostrar las peliculas por su genero usando Params
GET http://localhost:1234/movies?genre=Action
###
GET http://localhost:1234/movies?year=1994

###
GET http://localhost:1234/movies?director=Roger%20Allers


### POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama",
    "Thriller"
  ]
}

### PATCH 
PATCH http://localhost:1234/movies/06d537cd-f872-11ee-a6cb-0a0027000009
Content-Type: application/json

{
  "year": 2010,
  "genre": [
  "Action",
  "Adventure",
  "Sci-Fi"
  ]
}

### DELETE
DELETE http://localhost:1234/movies/64b3be1d-fbaf-11ee-a0a2-0a0027000009